'''Task 1
Practise type annotations
Go to your implementation of the Phonebook application from module 1 or any other comprehensive code,
which you have done during the course, and annotate this code with type hints, using knowledge from this lesson.

Task 2
Mypy check
Use Mypy project (https://github.com/python/mypy) to perform static type check ing of your code.
Play around a little bit with Mypy, go through results and reports generated by running the mypy,
perform refactoring based on the mentioned results.
'''

import json
import sys

from phonebook4_func_2 import add_contact, first_name_search, last_name_search, full_name_search, phone_search, \
    city_search

print(sys.argv)
if len(sys.argv) < 2:
    print('Please specify json file name')
    exit()
filename = sys.argv[1]
json_file = open(filename)
try:
    phonebook: list = json.load(json_file)
except json.decoder.JSONDecodeError:
    phonebook = []

if type(phonebook) != list:
    phonebook = []
json_file.close()
dict_pattern: dict = {
    'first_name': '',
    'last_name': '',
    'full_name': '',
    'phone': '',
    'city': ''
}
try:
    while True:
        command: str = input('''Select command from the list: 
			add - to add new contact
			search - to find a contact
			exit - to exit the phonebook
			: ''').strip().lower()
        if command == 'add':
            add_contact(dict_pattern, phonebook)
        elif command == 'search':
            while True:
                search_method: str = input('''choose a search method:
					1. search by first name
					2. search by last name
					3. search by full name
					4. search by phone number
					5. search by city
					6. return to main menu
					 ''')
                if search_method == '1':
                    first_name_search(phonebook)
                elif search_method == '2':
                    last_name_search(phonebook)
                elif search_method == '3':
                    full_name_search(phonebook)
                elif search_method == '4':
                    phone_search(dict_pattern, phonebook)
                elif search_method == '5':
                    city_search(phonebook)
                elif search_method == '6':
                    break
                else:
                    continue
        elif command == 'exit':
            print('Thx for using phonebook!')
            break
except Exception as e:
    print('Unexpected error')
    print(e)
finally:
    with open(filename, 'w') as json_file:
        json.dump(phonebook, json_file, indent=4)
